services:
  postgres:
    image: postgres:16-alpine
    container_name: ttserver-postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  artemis:
    image: apache/activemq-artemis:latest
    container_name: ttserver-artemis
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ANONYMOUS_LOGIN: false
    ports:
      - "61616:61616"  # JMS port
      - "8161:8161"    # Web console
    volumes:
      - artemis_data:/var/lib/artemis/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  artemis_data:
    driver: local